logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    error:
        include-message: always
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/user_service
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
tokenSecret: jf9i4gju83nfl0

